# Generated by Django 5.1.5 on 2025-04-06 00:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('creation_time', models.DateTimeField(auto_now_add=True)),
                ('order_info', models.JSONField(blank=True, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('send_from', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='chat_from', to=settings.AUTH_USER_MODEL)),
                ('send_to', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='chat_to', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['creation_time'],
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Untitled', max_length=30)),
                ('description', models.CharField(max_length=200)),
                ('condition', models.CharField(max_length=200)),
                ('categories', models.CharField(max_length=200)),
                ('picture', models.FileField(blank=True, upload_to='')),
                ('content_type', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('upload_time', models.DateTimeField(auto_now_add=True)),
                ('delivery_choice', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('pickup_location', models.CharField(max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Auction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curr_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('start_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('creation_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('total_bids', models.IntegerField(default=0)),
                ('buyer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='tartantrade.item')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=50, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Payment'), ('paid', 'Paid'), ('shipped', 'Shipped'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(max_length=50)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('paid_time', models.DateTimeField(blank=True, null=True)),
                ('shipping_address', models.CharField(max_length=200)),
                ('remarks', models.TextField(blank=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders_as_buyer', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='tartantrade.item')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders_as_seller', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_time'],
            },
        ),
        migrations.CreateModel(
            name='RatingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('rating_message', models.CharField(max_length=200)),
                ('sendfrom', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ratings_sent', to=settings.AUTH_USER_MODEL)),
                ('sendto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ratings_received', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.FileField(blank=True, upload_to='')),
                ('content_type', models.CharField(max_length=50)),
                ('itemsBought', models.ManyToManyField(related_name='buying', to='tartantrade.item')),
                ('itemsSold', models.ManyToManyField(related_name='selling', to='tartantrade.item')),
                ('itemsfav', models.ManyToManyField(related_name='saveforlater', to='tartantrade.item')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('rating', models.ManyToManyField(related_name='ratings', to='tartantrade.ratingitem')),
            ],
        ),
        migrations.CreateModel(
            name='ReportItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=200)),
                ('report_time', models.DateTimeField()),
                ('send_from', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='report_from', to=settings.AUTH_USER_MODEL)),
                ('send_to', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='report_to', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
